FROM debian:bookworm-slim

ENV LANG=C.UTF-8

RUN set -eux; \
    apt-get update -y; \
    apt-get install -y --no-install-recommends \
      # Non-ruby specific dependencies
      pkg-config ca-certificates curl m4 libtool automake autoconf build-essential libxml2-dev \
      # Ruby specific dependencies
      libsodium23 libreadline-dev zlib1g-dev libssl-dev libjemalloc-dev autoconf patch \
      libyaml-dev libgmp-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev uuid-dev \
    ; \
    # Install Rust (needed for YJIT)
    #   Note: Unfortunately stock rustc package didn't work, so we have to install it manually to compile ruby
    rustArch=; \
  	dpkgArch="$(dpkg --print-architecture)"; \
  	case "$dpkgArch" in \
  		'amd64') rustArch='x86_64-unknown-linux-gnu'; rustupUrl='https://static.rust-lang.org/rustup/archive/1.26.0/x86_64-unknown-linux-gnu/rustup-init'; rustupSha256='0b2f6c8f85a3d02fde2efc0ced4657869d73fccfce59defb4e8d29233116e6db' ;; \
  		'arm64') rustArch='aarch64-unknown-linux-gnu'; rustupUrl='https://static.rust-lang.org/rustup/archive/1.26.0/aarch64-unknown-linux-gnu/rustup-init'; rustupSha256='673e336c81c65e6b16dcdede33f4cc9ed0f08bde1dbe7a935f113605292dc800' ;; \
  	esac ; \
    mkdir -p /tmp/rust ; \
    curl -fsSLo /tmp/rust/rustup-init "${rustupUrl}" && \
    echo "${rustupSha256} */tmp/rust/rustup-init" | sha256sum --check --strict && \
    chmod +x /tmp/rust/rustup-init && \
    export RUSTUP_HOME='/tmp/rust/rustup' CARGO_HOME='/tmp/rust/cargo' && \
    export PATH="$CARGO_HOME/bin:$PATH" && \
    /tmp/rust/rustup-init -y --no-modify-path --profile minimal --default-toolchain 1.74.1 --default-host "${rustArch}" && \
    rustc --version && \
    cargo --version \
    ; \
    # Install Ruby
    mkdir /tmp/ruby-build && \
    cd /tmp/ruby-build && \
    curl -fsSLo ruby-build.tar.gz "https://github.com/rbenv/ruby-build/archive/refs/tags/v20250610.tar.gz" && \
    tar -C /tmp/ruby-build -xf ruby-build.tar.gz && \
    /tmp/ruby-build/ruby-build-20250610/install.sh /tmp/ruby-build && \
    CONFIGURE_OPTS="--with-jemalloc --enable-yjit --disable-install-doc" ruby-build 3.4.4 /usr/local --verbose && \
    cd && rm -Rf /tmp/ruby-build \
    ; \
    # Remove leftovers
    apt-mark auto '.*' > /dev/null ; \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false ; \
    rm -rf /var/lib/apt/lists/*
